server:
  port: 8280

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

spring:
  application:
    name: recipe-olive-insurance-gateway-service
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        instance-id: recipe-olive-insurance-gateway-service-8280
        health-check-path: /actuator/health
        health-check-interval: 15s
    gateway:
      routes:
        - id: recipe-olive-insurance-administration-service
          uri: lb://recipe-olive-insurance-administration-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /api/v1/${segment}
        - id: recipe-olive-insurance-auth-service
          uri: lb://recipe-olive-insurance-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/v1/${segment}
        - id: recipe-olive-insurance-settings-service
          uri: lb://recipe-olive-insurance-settings-service
          predicates:
            - Path=/settings/**
          filters:
            - RewritePath=/settings/(?<segment>.*), /api/v1/${segment}
        - id: recipe-olive-insurance-pricing-service
          uri: lb://recipe-olive-insurance-pricing-service
          predicates:
            - Path=/pricing/**
          filters:
            - RewritePath=/pricing/(?<segment>.*), /api/v1/${segment}
        - id: recipe-olive-insurance-attestation-service
          uri: lb://recipe-olive-insurance-attestation-service
          predicates:
            - Path=/attestations/**
          filters:
            - RewritePath=/attestations/(?<segment>.*), /api/v1/${segment}
        - id: recipe-olive-insurance-exploitation-service
          uri: lb://recipe-olive-insurance-exploitation-service
          predicates:
            - Path=/exploitation/**
          filters:
            - RewritePath=/exploitation/(?<segment>.*), /api/v1/${segment}
        - id: catch-all-route
          uri: no://op
          predicates:
            - Path=/{segment}**
          filters:
            - SetStatus=404
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "https://dev.olive.zeitune.tech"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    reactor.netty: INFO