server:
    port: 8180

spring:
    application:
        name: dev_olive_insurance_gateway_service

    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                enabled: true

        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
