spring:
    application:
        name: gateway-service
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                enabled: true
                instance-id: ${spring.application.name}:${random.value}
                health-check-path: /actuator/health
                health-check-interval: 15s
        gateway:
            routes:
                - id: olive-insurance-administration-service
                  uri: lb://olive-insurance-administration-service
                  predicates:
                      - Path=/admin/**
                  filters:
                      - RewritePath=/admin/(?<segment>.*), /api/v1/${segment}
                - id: olive-insurance-auth-service
                  uri: lb://olive-insurance-auth-service
                  predicates:
                      - Path=/auth/**
                  filters:
                      - RewritePath=/auth/(?<segment>.*), /api/v1/${segment}
                - id: olive-insurance-attest-service
                  uri: lb://olive-insurance-attest-service
                  predicates:
                      - Path=/attestations/**
                  filters:
                      - RewritePath=/attestations/(?<segment>.*), /api/v1/${segment}
                - id: olive-insurance-settings-service
                  uri: lb://olive-insurance-settings-service
                  predicates:
                      - Path=/settings/**
                  filters:
                      - RewritePath=/settings/(?<segment>.*), /api/v1/${segment}
                - id: olive-insurance-exploitation-service
                  uri: lb://olive-insurance-exploitation-service
                  predicates:
                      - Path=/exploitation/**
                  filters:
                      - RewritePath=/exploitation/(?<segment>.*), /api/v1/${segment}
server:
    port: 8080
management:
    endpoints:
        web:
            exposure:
                include: health,info,gateway