server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
spring:
  application:
    name: olive-insurance-gateway-service
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-8080
        health-check-path: /actuator/health
        health-check-interval: 15s
    gateway:
      routes:
        - id: olive-insurance-administration-service
          uri: lb://olive-insurance-administration-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*), /api/v1/${segment}
        - id: olive-insurance-auth-service
          uri: lb://olive-insurance-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/v1/${segment}
        - id: olive-insurance-settings-service
          uri: lb://olive-insurance-settings-service
          predicates:
            - Path=/settings/**
          filters:
            - RewritePath=/settings/(?<segment>.*), /api/v1/${segment}
        - id: olive-insurance-princing-service
          uri: lb://olive-insurance-princing-service
          predicates:
            - Path=/princing/**
          filters:
            - RewritePath=/princing/(?<segment>.*), /api/v1/${segment}
            #                - id: olive-insurance-attest-service
            #                  uri: lb://olive-insurance-attest-service
            #                  predicates:
            #                      - Path=/attestations/**
            #                  filters:
            #                      - RewritePath=/attestations/(?<segment>.*), /api/v1/${segment}
            #                - id: olive-insurance-exploitation-service
            #                  uri: lb://olive-insurance-exploitation-service
            #                  predicates:
            #                      - Path=/exploitation/**
            #                  filters:
            #                      - RewritePath=/exploitation/(?<segment>.*), /api/v1/${segment}
            # Nouvelle route pour les endpoints problématiques
        - id: catch-all-route
          uri: no://op  # Route factice
          predicates:
            - Path=/{segment}**
          filters:
            - SetStatus=404
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "https://dev.olive.zeitune.tech"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway.handler.FilteringWebHandler: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    org.springframework.http.codec: DEBUG
    reactor.netty: DEBUG
